### ISSUE TITLE
Why not returning more information in onError callback

### ISSUE THREAD

**Issue by AdamGrzybkowski** [dsrees/JavaPhoenixClient#13]
Sometimes you might want to check responseCode or sth when your WS connection fails.

Maybe it would be worth considering returning sth different than just Throwable?

**Comment by dsrees** [comment]
The `Error` that is passed to the `onError` callback is of type [WSError](https://github.com/daltoniam/Starscream/blob/master/Sources/Starscream/WebSocket.swift#L54) from the Starscream library which provides an ErrorType, Message, and Code. 

Does casting to this error help provide more usable context to the error?

**Comment by dsrees** [comment]
Agreed! I'll take a look into improving the onError callback to also accept the `Response` from the OKHttp WebSocket.

**Comment by dsrees** [comment]
Resolved in [0.1.3](https://github.com/dsrees/JavaPhoenixClient/releases/tag/0.1.3)
