### ISSUE TITLE
Missing proguard rules in README.md

### ISSUE THREAD

**Issue by AdamGrzybkowski** [dsrees/JavaPhoenixClient#15]
The library in the current state will not work when using proguard.

`PhxMessage` class member names are used to parse the response from WS.
The solution would be to add `@SerializeName` annotation, this way there is no need to add any additional proguard rules (apart from the ones for gson and okhhtp).

As for now you have to specify a rule like this
`-keepclassmembernames class org.phoenixframework.PhxMessage { *; }`

**Comment by dsrees** [comment]
Resolved in [0.1.3](https://github.com/dsrees/JavaPhoenixClient/releases/tag/0.1.3)
