### ISSUE TITLE
java.lang.NoClassDefFoundError: org.phoenixframework.PhxSocket for api<24

### ISSUE THREAD

**Issue by squarest** [dsrees/JavaPhoenixClient#27]
Hello! i have this error on all devices with api<24.
```
java.lang.NoClassDefFoundError: org.phoenixframework.PhxSocket$1$1
        at org.phoenixframework.PhxSocket.<init>(PhxSocket.kt:123)
```

 it's impossible to use your lib with this problem. I saw   you commited solution for this problem, but it's not released. Is it working? will you release it? when?

**Comment by dsrees** [comment]
Sorry, been busy. I'll work on getting that release out.

**Comment by dsrees** [comment]
0.1.4 is released
