### ISSUE TITLE
Remove GSON dependency

### ISSUE THREAD

**Issue by dsrees** [dsrees/JavaPhoenixClient#3]
Ideally, the User of this client should be able to use any JSON library of their choosing. Initial thought is to create a `JsonConverter` interface that accepts raw JSON string and has it pass back the decoded object that we need. This would also require a `Builder` of some sort to construct the `PhxSocket` class with the `JsonConverter`

Any ideas are welcome on this.

**Comment by eyal-lezmy** [comment]
If you want to delegate to the user the JSON parsing, add ing a JsonConverter inteface as a dependency seems to be a good idea. The counterpart is that it ask more work to your user.

But if your goal is to "simply" get rid of the GSON dependency, maybe a good thing would be to use the JSON libraries already existing into your JAVA or Kotlin standard libraries.

- For Java there is no portable solution covering the Java JDK and Android at the same time. If you choose to support one of the platforms you can use the native JSON libraries they are embedding.
- For Kotlin there is [a serialization library](https://github.com/Kotlin/kotlinx.serialization) that is aimed to be part of Kotlin 1.3. So far it is experimental, it is maybe not a good idea to add it to the project for now.

The advantage of using a standard lib is that nothing else is asked to the user than just working on it's own logic. It will increase a lot the on boarding of the library.

Considering Gson is not that big and many developers are already adding it to their projects, I would advise to not taking care of it as soon as kotlinx.serialization is part of the Kotlin sdt lib.

**Comment by dsrees** [comment]
@eyal-lezmy thanks for the input! I haven't decided the best approach here but these are some very good points. I've considered maybe breaking the project into a `core` and `gson` packages so you can decide which one you want to use.

The goal is to make as light-weight of a client as possible with as few dependencies as possible. I will probably wait until the kotlin.serialization is standardized though before moving on this.

**Comment by Maradox** [comment]
I would also like to swap in another JSON-library. Is this still something you are considering?

**Comment by dsrees** [comment]
@Maradox 0.6.0 has been released which supports a custom `encode` and `decode` functions, which matches the JS and Swift client APIs. See the README or `Defaults.kt` for implementation details.

GSON is still a dependency and I don't plan on changing that anytime soon so I will be closing this issue
