### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MarkPare** [dsrees/JavaPhoenixClient#30]
This library seems very useful. However, the documentation is pretty minimal which makes it hard to get up and running quickly. I'm a beginner/intermediate Android dev and intermediate/advanced Elixir dev and I still haven't figured out how to connect successfully  #29.

I may be doing something plainly wrong, but the docs aren't helping me much. I'd be happy to make a PR with more detailed documentation for getting started if others agree. @dsrees

**Comment by dsrees** [comment]
There is usage information in the wiki: https://github.com/dsrees/JavaPhoenixClient/wiki
