### ISSUE TITLE
Lots of Timers created

### ISSUE THREAD

**Issue by dustinconrad** [dsrees/JavaPhoenixClient#38]
For every channel push a new timer (and thus a new thread) is created.  This is quite expensive compared to using a ScheduledThreadPoolExecutor which would be re-using threads.

I plan on trying to convert all usages of Timers to using a shared ScheduledThreadPoolExecutor later in the week if this seems like a good change.

**Comment by dsrees** [comment]
done in #42

**Comment by dsrees** [comment]
Implemented in #43
