### ISSUE TITLE
Allow the underlying OkHttp Client to be configured

### ISSUE THREAD

**Issue by dsrees** [dsrees/JavaPhoenixClient#4]
Expose the OkHttp client to be configurable while creating the `PhxSocket`.  See the issue [#69](https://github.com/eoinsha/JavaPhoenixChannels/issues/69) on the JavaPhoenixChannels repo

**Comment by eyal-lezmy** [comment]
@AdamGrzybkowski do you plan to submit a PR about your patch for this? 
[Injecting the OkHttp client from the Socket constructor](https://github.com/AdamGrzybkowski/JavaPhoenixClient/commit/cc6e3ad2d6bc8d764bb9aa351c0bae50dbade284) seems a good idea. If you don't have time I will probably do it very soon.

We plan to use this lib and we will need to  inject our client too.

@dsrees do you agree with this simple solution?

**Comment by dsrees** [comment]
Yeah that seems like a viable solution

**Comment by dsrees** [comment]
@eyal-lezmy I'll actually get this in today. I have to make a couple small adjustments already so i'll just wrap this into the changes

**Comment by dsrees** [comment]
Resolved in [0.1.3](https://github.com/dsrees/JavaPhoenixClient/releases/tag/0.1.3)
