### ISSUE TITLE
ReconnectAfterMs is too big

### ISSUE THREAD

**Issue by ostap0207** [dsrees/JavaPhoenixClient#40]
JS version goes up to 10 seconds https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L729, 
here we go up to 100 seconds https://github.com/dsrees/JavaPhoenixClient/blob/master/src/main/kotlin/org/phoenixframework/PhxSocket.kt#L49.
Is that on purpose or a simple typo?

**Comment by dsrees** [comment]
that would be a typo
