### ISSUE TITLE
Reconnection strategy documentation

### ISSUE THREAD

**Issue by AdamGrzybkowski** [dsrees/JavaPhoenixClient#53]
Hi @dsrees 
I wanted to update the library but I see that a lot has changed. 

Could you provide a bit more information about reconnection strategy?

The reason I'm asking this is that I do have my own reconnection strategy for WS errors and know it would be duplicated with the one provided from the library. 
I do see that you do retry only for specific errors and I'm wondering if it would be possible to maybe implement this is a bit more configurable way? So we could choose the strategy like only for errors or when the WS was closed or both. Does it make sense?

**Comment by dsrees** [comment]
Definitely. I'm always glad to try to make the client more configurable.

Basically, the client will attempt a reconnect when the underlying socket
receives any kind of IOException.

Could you share what your code is doing to determine when to reconnect?

**Comment by AdamGrzybkowski** [comment]
In my case there is one requirement: 
The WS connection has to be open no matter what as long as users did not terminate it by closing the app/screen. 

So I do try to reconnect on every error.

**Comment by AdamGrzybkowski** [comment]
@dsrees I went through the code and here is what I found:
1. I think you are closing the WS with wrong error when the heartbeat is times out. [Here](https://github.com/dsrees/JavaPhoenixClient/blob/master/src/main/kotlin/org/phoenixframework/Socket.kt#L384) you should probably pass `WS_CLOSE_SOCKET_EXCEPTION` if you want to trigger reconnectTimer.
2. The next problem is in the same line. You are calling `this.connection?.disconnect(...)` but this basically tries to call `.close(...)` on the OkHttp Websocket. This does not work because the WS is already closed so no callback will be returned.

I've been able to reproduce this problem using android emulator and [Network Link Conditioner](https://nshipster.com/network-link-conditioner/)

On a side note. I was a bit confused when I saw [this ](https://github.com/dsrees/JavaPhoenixClient/blob/master/src/main/kotlin/org/phoenixframework/Transport.kt#L137). Don't you think it is strange that this is in a `Transport` class just to trigger reconnectTimer in the `Socket` when all of the reconnection logic is in that class. Is there any reason why this is not handled in the Socket?

**Comment by AdamGrzybkowski** [comment]
One more thing. The reconnectTimer will be scheduler only *once*. Because it is never scheduled again after its callback is invoked. This could be simply fixed by scheduling it [here](https://github.com/dsrees/JavaPhoenixClient/blob/master/src/main/kotlin/org/phoenixframework/Socket.kt#L194).
The one thing I'm not sure about is how it will work with the `Channel.rejoinTimer`. This one is being scheduled properly but if the connection is dropped it won't be able to reestablish the WS connection. 
WDYT?

**Comment by dsrees** [comment]
@AdamGrzybkowski Thanks for digging into this! It's appreciated. I'll be able to look into this more this weekend

**Comment by dsrees** [comment]
Made a few changes over the weekend. Need to update the tests to match. Will update when I get closer to fixing these up.

**Comment by dsrees** [comment]
I've resolved the issues regarding the heartbeat timing out and made some changes to the `Transport` layer to better mimic the JS websocket protocol.

Leaving this issue open since I'll still need to investigate the `reconnectTimer` only being scheduled once

**Comment by dsrees** [comment]
`reconnectTimer` will be scheduled each time the connection is closed. Changes will be available in the next release
