### ISSUE TITLE
Decoding message payloads

### ISSUE THREAD

**Issue by rawnsley** [dsrees/JavaPhoenixClient#54]
Is this the best way to extract data from the Message.payload or am I missing a trick?

    private fun onPhoenixOpen(m : Message) {
        val response = m.payload["response"] as LinkedTreeMap<*, *>
        val permissionsTokenEncoded = response.get("perms_token")
    }

LinkedTreeMap is an implementation detail that's leaking out of JavaPhoenixClient and I would rather avoid it, especially if you plan to switch to the built-in serialization library in future.

**Comment by dsrees** [comment]
`payload` is just a `Map<String, Any>` where `Any` can be another `Map<String, Any>. LinkedTreeMap is part of Gson, which is what is being used under the hood to convert raw text json into the `Message` object. 

Here's an example of how I typically use it

```Kotlin
val response = message.payload["response"] as? Map<*, *>

// Either access a key directly
val token = response?.get("token") as? String

// Choose to map the response to an Object
val myObj = gson.fromJson(gson.toJsonTree(response), MyObj::class.java)
val token = myObjc.token
```

Does that help?

**Comment by rawnsley** [comment]
@dsrees Thanks for the quick response. I'll experiment with both approaches.
