### ISSUE TITLE
JSON serialization defaults modify property names

### ISSUE THREAD

**Issue by rawnsley** [dsrees/JavaPhoenixClient#71]
When serializing Payload objects, the default JSON behaviour is to convert from camel case to snake case: https://github.com/dsrees/JavaPhoenixClient/blob/master/src/main/kotlin/org/phoenixframework/Defaults.kt#L52

I presume it was done deliberately for internal reasons, but it is a bit of a surprise.

I don't think this is what the equivalent Javascript library does: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L648

**Comment by dsrees** [comment]
Ideally I would like to make the parser customizable to the User so you can use any serializer/deserializer you would like and configured in any way

**Comment by dsrees** [comment]
@rawnsley Looking over this again, and you can pass your own `Gson` instance to your `Socket`

```Kotlin
val myGson = GsonBuilder()
        .setLenient()
        .setFieldNamingPolicy(FieldNamingPolicy.UPPER_CAMEL_CASE)
        .create()

socket = Socket(
        url = "wss://localhost:4000/socket",
        gson = myGson
    )
```
