### ISSUE TITLE
jcenter shutdown - February 2022

### ISSUE THREAD

**Issue by ryanlchandler** [dsrees/JavaPhoenixClient#76]
[https://blog.gradle.org/jcenter-shutdown](https://blog.gradle.org/jcenter-shutdown)

I stumbled across this today when I was unable to fetch this dependency.  Do you have plans to publish somewhere else?

**Comment by dsrees** [comment]
I do, i just haven't been able to allocate time to this. Sorry for the lapse in availability. I'll update here when I get that fixed

**Comment by dsrees** [comment]
JavaPhoenixClient is now hosted on maven central. Future releases will not be uploaded to jcenter.

https://search.maven.org/artifact/com.github.dsrees/JavaPhoenixClient/0.3.4/jar

**Comment by ryanlchandler** [comment]
Awesome!  Thank you!!
