### ISSUE TITLE
Tries to reconnect with invalid token

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [dsrees/JavaPhoenixClient#82]
If the connection is lost the library automatically tries to reconnect.
However, if one of the initial `Socket` params was an access token and the token expired in the meantime it will nevertheless be reused for the reconnect attempt. This leads to the server not accepting the reconnect requests.

We need some way to take over the reconnect strategy in the library client. Either a callback where we can pass new parameters or a way to disable the reconnect and handle it ourselves.

**Comment by dsrees** [comment]
0.5.0 released with this. Readme has been updated with an example as well.

```kotlin
// Create the Socket
var authToken = "abc"
val socket = Socket("http://localhost:4000/socket/websocket", { mapOf("token" to authToken) })
```

**Comment by lukasz-kalnik-gcx** [comment]
Thank you so much for your quick reaction and your effort! I will test it immediately 🙏

**Comment by dsrees** [comment]
👍🏼 of course! It was a feature in the SwiftPhoenixClient already that I had forgotten to port over.
